services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: zer
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zer -d restaurant_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://zer:password@postgres:5432/restaurant_db"
      RESEND_API_KEY: "blablabla"
      FROM_EMAIL: ""
      FRONTEND_URL: "http://localhost:5173"
      JWT_ACCESS_SECRET: "SECRET123"
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run seed && npm run dev"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3001/api"
      VITE_SOCKET_URL: "http://localhost:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  prisma-studio:
    build: ./backend
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://zer:password@postgres:5432/restaurant_db"
    depends_on:
      - postgres
      - backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npx prisma studio --port 5555 --browser none

volumes:
  postgres_data:



# services:
#   postgres:
#     image: postgres:15
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data"

#   backend:
#     build: ./backend
#     ports:
#       - "3000:3000"
#     environment:
#       DATABASE_URL: ${DATABASE_URL}
#       PORT: ${PORT:-3000}
#     depends_on:
#       - postgres
#     volumes:
#       - ./backend:/app
#       - /app/node_modules
#     command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run seed && npm run start"

#   frontend:
#     build: ./frontend
#     ports:
#       - "5173:5173"
#     environment:
#       - VITE_API_URL=${VITE_API_URL}
#     depends_on:
#       - backend
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     command: npm run build && npm run preview -- --host

# volumes:
#   postgres_data: